# Generated by Django 5.2.7 on 2025-10-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_food_description_alter_food_image_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
