# Generated by Django 5.2.7 on 2025-10-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_footer_phone_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='instagram',
            field=models.CharField(default='default text', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='telegram',
            field=models.CharField(default='default text', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='whatsapp',
            field=models.CharField(default='default text', max_length=100),
        ),
    ]
