# Generated by Django 5.2.7 on 2025-10-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_food_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='id',
            new_name='productid',
        ),
    ]
