# Generated by Django 5.2.8 on 2025-11-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_id_food_productid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
