# Generated by Django 5.2.7 on 2025-10-27 13:00

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
