# Generated by Django 5.2.8 on 2025-11-06 11:20

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
