# Generated by Django 5.2.8 on 2025-11-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_created_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tedad',
            field=models.IntegerField(),
        ),
    ]
