# Generated by Django 5.2.8 on 2025-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_food_options_food_created_food_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
