# Generated by Django 5.2.8 on 2025-11-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category'),
        ('products', '0004_alter_food_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-updated'], 'verbose_name': 'Food'},
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, to='home.category'),
        ),
    ]
