# Generated by Django 5.2.8 on 2025-11-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_food_options_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='tag',
        ),
    ]
