# Generated by Django 5.2.8 on 2025-11-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='situation',
            field=models.BooleanField(default=False),
        ),
    ]
